[build]
  base = "."
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/blog/long-tail-domain-keywords"
  to = "/blog/top-domaining-tools-for-investors-2025"
  status = 301
